### PR TITLE
Add uid param to configuration

### PR DESCRIPTION
**Pull request by francisco-navarro**
This field is needed to work with tuya api.

### CODE REVIEW

**Comment by codetheweb** [comment]
Thanks for your work; but the UID is not actually necessary.  Does your device work without it?

**Comment by francisco-navarro** [comment]
My device cannot connect without this field (I don't know why 😓). And with uid, it works perfectly.


``` javascript
/node/node-v7.9.0/lib/node_modules/homebridge-tuya-outlet/node_modules/tuyapi/index.js:282
      client.write(buffer);
            ^

TypeError: Cannot read property 'write' of null
    at retryConnect.to (/node/node-v7.9.0/lib/node_modules/homebridge-tuya-outlet/node_modules/tuyapi/index.js:282:13)
    at Socket.handleError (/node/node-v7.9.0/lib/node_modules/homebridge-tuya-outlet/node_modules/net-retry-connect/index.js:21:13)
```

**Comment by codetheweb** [comment]
Strange.  Can you please start Homebridge with `DEBUG=* homebridge` and post the output here?

**Comment by francisco-navarro** [comment]
I don't know, but right now, is work. Sometimes is unreachable. I'll try get the error with DEBUG=* homebridge.

**Pull request closed without merging**
